# Generated by Django 3.0.7 on 2020-07-11 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autocomplete',
            old_name='title',
            new_name='words',
        ),
        migrations.RemoveField(
            model_name='autocomplete',
            name='qty',
        ),
    ]
